name: 'tar node action'
description: 'tar Node.js project'
inputs:
  ssh_host:
    description: "ssh host which define in ssh_config to connect"
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/ssh.sh ${{ inputs.ssh_host }}
      shell: bash

    - run: ${{ github.action_path }}/main.sh
      shell: bash
