name: test tar-node-action

on: [push]

jobs:
  test-job:

    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: ${{ secrets.SSH_CONFIG }}

    - uses: actions/checkout@v2

    - name: tar node
      uses: lqqyt2423/tar-node-action@0.0.8
      with:
        ssh_host: ${{ secrets.SSH_HOST }}
        ssh_host_project_path: ${{ secrets.SSH_HOST_PROJECT_PATH }}

    - run: pwd
    - run: echo done
      env:
        CI: true
