name: test tar-node-action

on: [push]

jobs:
  test-job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: lqqyt2423/tar-node-action@0.0.3
    - run: echo done
      env:
        CI: true
