name: test tar-node-action

on: [push]

jobs:
  test-job:

    runs-on: ubuntu-latest

    steps:
    - run: pwd
    - uses: lqqyt2423/tar-node-action@0.0.2
    - run: echo done
      env:
        CI: true
