name: test tar-node-action

on: [push]

jobs:
  test-job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: pwd
    - uses: lqqyt2423/tar-node-action@0.0.2
    - run: type wget
    - run: type curl
    - run: type ssh
    - run: type node
    - run: echo done
      env:
        CI: true
